// Generated by CoffeeScript 1.6.2
/*
  Lutzen
*/

var Adjectives, Glues, Predicates, Subjects, adjectives, glues, i, lutzen, poesie, predicates, shuffle, subjects, _i;

Subjects = [["GRAF", 0], ["FREMDE", 0], ["BLICK", 0], ["KIRCHE", 1], ["SCHLOSS", 1], ["BILD", 2], ["AUGE", 2], ["DORF", 2], ["TURM", 0], ["BAUER", 0], ["WEG", 0], ["GAST", 0], ["TAG", 0], ["HAUS", 2], ["TISCH", 0], ["KNECHT", 0]];

Adjectives = "OFFEN STILL STARK GUT SCHMAL NAH NEU LEISE FERN TIEF SPAET DUNKEL FREI GROSS ALT WÜTEND".split(" ");

Glues = ["UND", "ODER", "SO GILT", ".", ".", ".", ".", "."];

Predicates = [["EIN", "EINE", "EIN"], ["JEDER", "JEDE", "JEDES"], ["KEIN", "KEINE", "KEINES"], ["NICHT JEDER", "NICHT JEDE", "NICHT JEDES"]];

shuffle = function(a) {
  var i, j, _i, _ref, _ref1;

  for (i = _i = _ref = a.length - 1; _ref <= 1 ? _i <= 1 : _i >= 1; i = _ref <= 1 ? ++_i : --_i) {
    j = Math.floor(Math.random() * (i + 1));
    _ref1 = [a[j], a[i]], a[i] = _ref1[0], a[j] = _ref1[1];
  }
  return a;
};

subjects = Subjects.concat(Subjects);

adjectives = Adjectives.concat(Adjectives);

glues = Glues.concat(Glues);

predicates = [];

for (i = _i = 0; _i < 8; i = ++_i) {
  predicates.push.apply(predicates, Predicates);
}

lutzen = function(lines) {
  var adjective1, adjective2, gender1, gender2, glue, l, predicate1, predicate2, sentence, subject1, subject2, _j, _results;

  _results = [];
  for (l = _j = 0; 0 <= lines ? _j < lines : _j > lines; l = 0 <= lines ? ++_j : --_j) {
    i = l % 16;
    if (i === 0) {
      [subjects, adjectives, glues, predicates].map(shuffle);
    }
    subject1 = subjects[i][0];
    subject2 = subjects[i + 15][0];
    gender1 = subjects[i][1];
    gender2 = subjects[i][1];
    predicate1 = predicates[i][gender1];
    predicate2 = predicates[i + 15][gender2];
    adjective1 = adjectives[i];
    adjective2 = adjectives[i + 15];
    glue = glues[i];
    sentence = [[predicate1, subject1, "IST", adjective1].join(" "), glue !== "." ? " " + glue + " " : "" + glue + " ", [predicate2, subject2, "IST", adjective2].join(" ")].join("");
    _results.push("" + sentence + ".");
  }
  return _results;
};

poesie = lutzen(1024);

console.log(poesie.join("\n"));
